### ISSUE TITLE
Transfer and update indices list

### ISSUE THREAD

**Issue by DamienIrving** [AusClimateService/model-evaluation#3]
Transfer [`climpact_xclim_indices.md`](https://github.com/AusClimateService/ccam-evaluation/blob/main/climpact_xclim_indices.md) to this repository and add a column for [icclim](https://icclim.readthedocs.io/en/stable/).

**Comment by ngben** [comment]
Added [indices.md](https://github.com/AusClimateService/model-evaluation/blob/master/indices.md) and updated with icclim column
